### PR TITLE
Automatically diff two exported databases (without requiring IDA!)

### PR DESCRIPTION
**Pull request by jarnovanleeuwen**
Hi,

This pull request adds functionality to allow for automatic diffing of two exported databases. The following environment variables should be set to make use of the functionality:

- DIAPHORA_AUTO_DIFF
- DIAPHORA_DB1
- DIAPHORA_DB2
- DIAPHORA_DIFF_OUT

Example usage:

`$ DIAPHORA_AUTO_DIFF=1 DIAPHORA_DB1=first.sqlite DIAPHORA_DB2=second.sqlite DIAPHORA_DIFF_OUT=diff.sqlite python diaphora.py`

The cool thing is that this approach does allow for batch diffing available databases, without requiring IDA to be available on the machine.

Greetings,
Jarno

### CODE REVIEW

**Comment by joxeankoret** [comment]
Hey! Thanks for the PR @jarnovanleeuwen, I will modify it a bit as I think that some things can be done better (i.e., checking again and again some environment variables, hiding classes, etc...)

**Comment by jarnovanleeuwen** [comment]
Yes, I can fully understand that since I was unfamiliar with Python. Thank you!

**Comment by joxeankoret** [comment]
Sorry for taking that long, I applied your PR:

3cf12e738dc3113f5bb682cd6170401269616f29

Thanks a lot!

**Comment by joeleong** [comment]
I tried to use this but got the following:
```
Traceback (most recent call last):
  File "diaphora/diaphora.py", line 3955, in <module>
    bd.diff(db2)
  File "diaphora/diaphora.py", line 3744, in diff
    self.find_unmatched()
  File "diaphora/diaphora.py", line 3627, in find_unmatched
    demangled_name = Demangle(str(name), INF_SHORT_DN)
NameError: global name Demangle is not defined
```

Did I misconfigure something? Seems like it relies on at least `idc.Demangle`.

**Comment by jarnovanleeuwen** [comment]
I noticed the same. joxeonkoret combined this PR with a bit of refactoring and accidentally reintroduced calls to `Demangle` and usage of the `INF_SHORT_DN` constant. I did a quick and dirty fix to get up and running again: https://github.com/jarnovanleeuwen/diaphora/commit/0af1c8bf9826ee518a1b20f4b1c47ae349992086.

I did not create a PR for this because it is not a good solution.

**Comment by joxeankoret** [comment]
I will be on holidays until next week. I will upload a proper fix by next week.

**Pull request closed without merging**
