### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by radare**

### CODE REVIEW

**Comment by joxeankoret** [comment]
IDA doesn't support Python 3. I haven't tested anything at all with Python 3. I'm not going to accept this, as it makes no sense to me.

**Comment by jvoisin** [comment]
Binary Ninja supports Python3, and so does radare2.

Python2 [won't be supported anymore in two years]( http://legacy.python.org/dev/peps/pep-0373/ ), odds are that you'll need to transition anyway once IDA makes the jump, why reject this pull-request?

**Comment by joxeankoret** [comment]
If people consider that it's relevant, I will add. But I don't think it's the time for doing so at all because there is no real reason.

**Comment by jvoisin** [comment]
It's relevant for radare2 and binary ninja, it doesn't break anything, and makes diaphora more future-proof, those are good reasons :/

**Comment by joxeankoret** [comment]
OK, I will modify the patch so no messages with parenthesis appear and apply it...

**Comment by trufae** [comment]
https://pythonclock.org/

**Comment by joxeankoret** [comment]
I will add it, at some point. However, better than sending me patches for this, I would prefer patches for this: https://github.com/joxeankoret/diaphora/issues/99

**Comment by piratesephiroth** [comment]
Python is a mess anyway and I'm not touching it with a 10-feet pole.
I can't wait for them to release v4, lmao

**Comment by joxeankoret** [comment]
Your comments are very useful.

**Comment by joxeankoret** [comment]
Very useful comments.

**Comment by wargio** [comment]
@joxeankoret any news regarding Py3 support? this PR looks promising on this topic.

**Comment by joxeankoret** [comment]
It's already ported to Python 3 in my development version but I'm fighting with some IDA 7.4 problems.

**Comment by thestr4ng3r** [comment]
radare2 has no IDA 7.4 problems, just saying...

**Comment by joxeankoret** [comment]
Stop trolling. Thanks.

**Comment by thestr4ng3r** [comment]
Sorry :see_no_evil: But honestly I'm looking forward to the Python 3 support, this might motivate one of us to bring the r2 integration back in a proper way.

**Comment by joxeankoret** [comment]
Sorry, but I don't mind. And the reason is easy: look at the messages in this thread, especially to the message where I ask for someone to fix issue #99, and then guess what is my opinion about putting any kind of effort into porting Diaphora to Radare2.

**Pull request closed without merging**
