### PR TITLE
Separate IDA components and refactor to use inheritance

### PR DESCRIPTION
**Pull request by joeleong**
Hi,

I tried to separate out the IDA components into another file (`diaphora_ida.py`). The hope is to make it easier to maintain and use without IDA. Big thanks to @jarnovanleeuwen for his patches that this is supposed to extend. I pretty much just cut/pasted the pieces of code that he was conditionally defining and tried to eliminate duplicate code where I could via inheritance. 

`diaphora_ida.py` should be a drop-in replacement for the old `diaphora.py` if you're running it from IDA and you can run something like the following for command line use:

```
python diaphora.py ver_1.sqlite ver_2.sqlite -o ver_1_vs_2.diaphora
```

Threw in a couple bug fixes for cases where the decompiler plugin hadn't loaded yet and when the MD5's match between two DB's.

Let me know what you think.

Thanks for the tool!

### CODE REVIEW

**Comment by joxeankoret** [comment]
Thanks a lot! This is something I have wanted to do since long ago but never did finally. I will be on holidays until next week but be sure I will implement the PR as soon as I'm back.

**Comment by joxeankoret** [comment]
Hi,

It needs a bit of testing from my side. I will try to do it for today.

**Comment by joxeankoret** [comment]
As I expected, after pushing some patches the PR is broken :/ I'm trying to fix it manually...

**Comment by joeleong** [comment]
Tried to resolve the conflicts. Please test when you get a chance. Let me know if you have comments.

Thanks!

**Comment by joxeankoret** [comment]
Merged + added some little modifications e1f97e4612e8cce20a06f095233cff51606cf5b3. Thanks a lot for the PR!

**Pull request merged**
